language: php

php:
  - 5.4
  - 5.5
  - hhvm

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - composer self-update
  - composer update
  - php vendor/sulu/test-bundle/Sulu/Bundle/TestBundle/Testing/GeneratePhpunitConfig.php $DB
  - ./vendor/sulu/test-bundle/Sulu/Bundle/TestBundle/Resources/bin/travis.sh dbal

script: phpunit -c $DB.phpunit.xml

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: hhvm
      env: DB=pgsql  # driver currently unsupported by HHVM
