language: php

php:
  - 5.5
  - 5.4

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install
  - php vendor/sulu/test-bundle/Sulu/Bundle/TestBundle/Testing/GeneratePhpunitConfig.php $DB
  - ./vendor/sulu/test-bundle/Sulu/Bundle/TestBundle/Resources/bin/travis.sh dbal

script: phpunit --coverage-text
