language: php

php:
  - 5.4
  - 5.5
  - hhvm

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - composer self-update
  - composer update
  - ./bin/jackrabbit.sh
  - php vendor/sulu/test-bundle/Sulu/Bundle/TestBundle/Testing/GeneratePhpunitConfig.php $DB
  - php bin/jackrabbit.php
  - ./vendor/sulu/test-bundle/Sulu/Bundle/TestBundle/Resources/bin/travis.sh

script: 
    - phpunit --group nodecontroller -c $DB.phpunit.xml --coverage-text
    - phpunit --group webtest -c $DB.phpunit.xml --coverage-text
    - phpunit --group preview -c $DB.phpunit.xml --coverage-text
    - phpunit --group repository -c $DB.phpunit.xml --coverage-text
    - phpunit --group content -c $DB.phpunit.xml --coverage-text
    - phpunit --group unit -c $DB.phpunit.xml --coverage-text

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: hhvm
      env: DB=pgsql  # driver currently unsupported by HHVM
